### ISSUE TITLE
runtime error when listening for changes in a folder different than "."

### ISSUE THREAD

**Issue by raffaeleguidi** [raffaeleguidi/watcherino#2]
panic: runtime error: slice bounds out of range [8:6]

goroutine 20 [running]:
main.Watcher.func1(0xc0000aa300, 0x7ffeefbffc83, 0x7, 0x1249da0, 0x1, 0x7ffeefbffc74, 0xe, 0x5)
        /Users/rguidi/develop/watcherino/watcherino.go:68 +0x318
created by main.Watcher
        /Users/rguidi/develop/watcherino/watcherino.go:61 +0x173

**Comment by raffaeleguidi** [comment]
the bug is fixed - only warning is that the "folder" parameter cannot be "." - it should always be a folder name without "." or "../" or whatever (no path algebra is supported)
